import Anthropic from '@anthropic-ai/sdk';
import { z } from 'zod';
import { env } from '@/lib/config';
import { BusinessProfile } from './places';

/**
 * Site section types
 */
export const SiteSectionSchema = z.discriminatedUnion('type', [
  z.object({
    type: z.literal('hero'),
    headline: z.string(),
    subheadline: z.string(),
    ctaText: z.string(),
    backgroundImageUrl: z.string().url().optional(),
  }),
  z.object({
    type: z.literal('services'),
    heading: z.string(),
    description: z.string(),
    services: z.array(
      z.object({
        name: z.string(),
        description: z.string(),
        price: z.string().optional(),
      })
    ),
  }),
  z.object({
    type: z.literal('about'),
    heading: z.string(),
    content: z.string(),
    imageUrl: z.string().url().optional(),
  }),
  z.object({
    type: z.literal('reviews'),
    heading: z.string(),
    reviews: z.array(
      z.object({
        author: z.string(),
        rating: z.number().min(1).max(5),
        text: z.string(),
      })
    ),
  }),
  z.object({
    type: z.literal('gallery'),
    heading: z.string(),
    imageUrls: z.array(z.string().url()),
  }),
  z.object({
    type: z.literal('cta'),
    heading: z.string(),
    description: z.string(),
    buttonText: z.string(),
  }),
  z.object({
    type: z.literal('contact'),
    heading: z.string(),
    phone: z.string().optional(),
    email: z.string().email().optional(),
    address: z.string().optional(),
  }),
]);

export type SiteSection = z.infer<typeof SiteSectionSchema>;

/**
 * Complete site document generated by AI
 */
export const SiteDocumentSchema = z.object({
  title: z.string(),
  description: z.string(),
  sections: z.array(SiteSectionSchema),
  ogImageUrl: z.string().url().optional(),
});

export type SiteDocument = z.infer<typeof SiteDocumentSchema>;

/**
 * AI adapter interface
 */
export interface AIAdapter {
  generateSiteDocument(business: BusinessProfile): Promise<SiteDocument>;
}

/**
 * Real Anthropic adapter
 */
export const anthropicAdapter: AIAdapter = {
  async generateSiteDocument(business: BusinessProfile): Promise<SiteDocument> {
    if (!env.ANTHROPIC_API_KEY) {
      throw new Error('ANTHROPIC_API_KEY required');
    }

    const client = new Anthropic({
      apiKey: env.ANTHROPIC_API_KEY,
    });

    const prompt = `You are a professional copywriter creating a website for a local business.

Business Information:
Name: ${business.name}
Description: ${business.description || 'No description provided'}
Address: ${business.address || 'Not provided'}
Phone: ${business.phone || 'Not provided'}
Website: ${business.website || 'Not provided'}
Categories: ${business.categories.join(', ')}
Rating: ${business.rating ? `${business.rating}/5 (${business.reviewCount} reviews)` : 'Not rated'}

Generate a compelling website content structure as a JSON object with this exact structure:
{
  "title": "Page title",
  "description": "Meta description",
  "sections": [
    {
      "type": "hero",
      "headline": "Main headline",
      "subheadline": "Supporting text",
      "ctaText": "Call to action button",
      "backgroundImageUrl": "https://via.placeholder.com/1920x600?text=Hero"
    },
    {
      "type": "about",
      "heading": "About section heading",
      "content": "Detailed about text",
      "imageUrl": "https://via.placeholder.com/600x400?text=About"
    },
    {
      "type": "services",
      "heading": "Services heading",
      "description": "Services intro",
      "services": [
        {
          "name": "Service name",
          "description": "Service description",
          "price": "Price range (optional)"
        }
      ]
    },
    {
      "type": "reviews",
      "heading": "What Our Customers Say",
      "reviews": [
        {
          "author": "Customer name",
          "rating": 5,
          "text": "Review text"
        }
      ]
    },
    {
      "type": "cta",
      "heading": "Ready to get started?",
      "description": "Call to action description",
      "buttonText": "Book Now"
    },
    {
      "type": "contact",
      "heading": "Contact Us",
      "phone": "${business.phone || ''}",
      "email": "${business.email || ''}",
      "address": "${business.address || ''}"
    }
  ],
  "ogImageUrl": "https://via.placeholder.com/1200x630?text=${encodeURIComponent(business.name)}"
}

Return ONLY valid JSON. Make the content compelling, professional, and specific to this business. Use the business name and details throughout.`;

    try {
      const message = await client.messages.create({
        model: 'claude-3-5-sonnet-20241022',
        max_tokens: 2000,
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
      });

      const content = message.content[0];
      if (content.type !== 'text') {
        throw new Error('Unexpected response type from Claude');
      }

      const jsonMatch = content.text.match(/\{[\s\S]*\}/);
      if (!jsonMatch) {
        throw new Error('No JSON found in response');
      }

      const parsed = JSON.parse(jsonMatch[0]);
      const validated = SiteDocumentSchema.parse(parsed);

      console.info('AI generated site document', {
        businessName: business.name,
        sections: validated.sections.length,
      });

      return validated;
    } catch (error) {
      console.error('AI generation failed:', error);
      throw error;
    }
  },
};

/**
 * Mock AI adapter (deterministic for testing)
 */
export const mockAIAdapter: AIAdapter = {
  async generateSiteDocument(business: BusinessProfile): Promise<SiteDocument> {
    console.log('MOCK: AI generates site for:', business.name);

    const doc: SiteDocument = {
      title: `${business.name} | Professional Services`,
      description:
        business.description || `Welcome to ${business.name}. Professional services in your area.`,
      sections: [
        {
          type: 'hero',
          headline: `Welcome to ${business.name}`,
          subheadline: business.description || 'Professional services tailored to your needs',
          ctaText: 'Book Now',
          backgroundImageUrl:
            business.photoUrls?.[0] || 'https://via.placeholder.com/1920x600?text=Hero',
        },
        {
          type: 'about',
          heading: 'About Us',
          content:
            business.description ||
            `${business.name} is committed to providing exceptional service with attention to detail and customer satisfaction.`,
          imageUrl: business.photoUrls?.[1] || 'https://via.placeholder.com/600x400?text=About',
        },
        {
          type: 'services',
          heading: 'Our Services',
          description: 'We offer a range of professional services to meet your needs.',
          services: [
            {
              name: 'Premium Service',
              description: 'Our flagship offering with white-glove service',
            },
            {
              name: 'Standard Service',
              description: 'High-quality service at an accessible price point',
            },
            {
              name: 'Quick Service',
              description: 'Fast, efficient service for those in a hurry',
            },
          ],
        },
        {
          type: 'reviews',
          heading: 'What Our Customers Say',
          reviews: business.topReviews.map((r) => ({
            author: r.author,
            rating: r.rating,
            text: r.text,
          })),
        },
        {
          type: 'cta',
          heading: 'Ready to experience our service?',
          description: 'Book your appointment today and discover why our customers love us.',
          buttonText: 'Book an Appointment',
        },
        {
          type: 'contact',
          heading: 'Get in Touch',
          phone: business.phone,
          email: business.email,
          address: business.address,
        },
      ],
      ogImageUrl: business.photoUrls?.[0] || 'https://via.placeholder.com/1200x630?text=Business',
    };

    return doc;
  },
};

/**
 * Get AI adapter based on environment
 */
export function getAIAdapter(): AIAdapter {
  return env.MOCK_MODE ? mockAIAdapter : anthropicAdapter;
}
